echo "What is your name?"
read PERSON
echo "Hello, $PERSON"
NAME="Zara Ali"
readonly NAME
echo "$NAME"
echo "$$"
echo "File Name: $0"
echo "First Parameter : $1"
echo "Second Parameter : $2"
echo "Quoted Values: $@"
echo "Quoted Values: $*"
echo "Total Number of Parameters : $#"

NAM[0]="a"
NAM[1]="b"
NAM[2]="c"
NAM[3]="d"
NAM[4]="e"
echo "First Method: ${NAM[*]}"
echo "Second Method: ${NAM[@]}"
