ASSUME CS:CODE,DS:DATA
DATA SEGMENT
        Var1 DW 0002H
        Var2 DW 0012H
DATA ENDS
CODE SEGMENT
START:MOV AX,DATA
      MOV DS,AX
      MOV AX,Var1
      MOV BX,Var2
      ADD AX,BX
      MOV AH,4CH
      INT 21H
CODE ENDS
END START
