
DATA SEGMENT
    VAR1 DW 0022H
    VAR2 DW 0022H
DATA ENDS
ASSUME CS:CODE,DS:DATA
CODE SEGMENT
   START:MOV AX,DATA
         MOV DS,AX
         MOV AX,VAR1
         MOV BX,VAR2
	 CLC
         DIV BX
         MOV AH,4CH
         INT 21H
CODE ENDS
END START
