DATA SEGMENT
        msg DB "HELLO WORLD$"
DATA ENDS
ASSUME CS:CODE,DS:DATA
CODE SEGMENT
START:MOV AX,DATA
      MOV DS,AX
      LEA DX,msg
      MOV AH,9
      INT 21H
      MOV AH,4CH
      INT 21H
ENDS
END START
